add_newline = false


format = "$directory$git_branch$git_status$memory_usage$character"

[directory]
format = "[$path]($style)[  ](bold blue)[$read_only]($read_only_style) "
truncation_length = 1
home_symbol = "  "

[character]
success_symbol = "[»](green)"
error_symbol = "[»](red)"
vicmd_symbol = "[«](green)"

[git_branch]
format = "[$symbol$branch]($style) "
